# Generated by Django 2.0.6 on 2018-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='ototal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
