# Generated by Django 2.1.1 on 2018-09-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_orders', '0004_auto_20180915_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetailinfo',
            options={'verbose_name': '订单详情表', 'verbose_name_plural': '订单详情表'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单信息表', 'verbose_name_plural': '订单信息表'},
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='count',
            field=models.IntegerField(verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_orders.OrderInfo', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oIsPay',
            field=models.BooleanField(default=False, verbose_name='是否付款'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(max_length=10, verbose_name='订单地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='odate',
            field=models.DateTimeField(auto_now=True, verbose_name='订单日期'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='ototal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='订单用户名'),
        ),
    ]
