# Generated by Django 2.1.1 on 2018-09-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_orders', '0006_auto_20180919_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='odate',
            field=models.DateTimeField(auto_now=True, verbose_name='订单日期'),
        ),
    ]
