# Generated by Django 2.0.5 on 2018-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20180914_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gjianjie',
            field=models.CharField(max_length=200, verbose_name='商品简介'),
        ),
    ]
