# Generated by Django 2.1.1 on 2018-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20180914_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(default='', max_length=20, verbose_name='商品名'),
        ),
    ]
