# Generated by Django 2.1.1 on 2018-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20180918_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(max_length=20, verbose_name='商品名'),
        ),
    ]
