# Generated by Django 2.1.1 on 2018-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20180914_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uemail',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='用户手机'),
        ),
    ]
