# Generated by Django 2.1.1 on 2018-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0004_auto_20180917_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uhistory',
            field=models.CharField(default='', max_length=200, verbose_name='历史记录'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uphone_num',
            field=models.CharField(default='', max_length=11, verbose_name='收货人手机'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default='', max_length=30, verbose_name='用户手机'),
        ),
    ]
