# Generated by Django 2.1.1 on 2018-09-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_areainfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areainfo',
            options={'verbose_name': '省市区表', 'verbose_name_plural': '省市区表'},
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='parea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.AreaInfo', verbose_name='上一级'),
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='title',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
    ]
