# Generated by Django 2.1.1 on 2018-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0009_auto_20180918_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='是否设为默认'),
        ),
    ]
