# Generated by Django 2.1.1 on 2018-09-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='df_user',
            new_name='user',
        ),
    ]
