# Generated by Django 2.1.1 on 2018-09-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_car', '0002_auto_20180915_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'verbose_name': '购物车表', 'verbose_name_plural': '购物车表'},
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='count',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户名'),
        ),
    ]
